apiVersion: v1
kind: Secret
metadata:
    name: libsql-secret
    namespace: messenger-clone
type: Opaque
stringData:
    jwt-key: ENC[AES256_GCM,data:IntFXV1frtaM/eWPhPTAEgqTYPKBarELocmEPOizYtwPMBVEJxynQBkpyPg=,iv:ZjMBnN5CaD+37/MGrcM4Fkx9fjBIXCl1RJDO8Yamius=,tag:YqLJ90yYPY1SrCLWPbp6Dw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaVlmdUJ6OUk1TXNTeWhZ
            ZHRoRmt5Tlh3NEZwTGxDcEthUC9SV1Qxa1ZzCjViOGhPU0pYNnNTRmJHZmFwb2Vo
            MUkvdHY0ZjJOSkJYQW5sRmt4SmJNUk0KLS0tIHIvaXhZazc2c1ZZMHJGd2hXWENp
            d3ZTZE1yeDVkYWFRUWYrOHZ6cTlZcVkKHnIYypUg491WBBuLKSHWNMp5mUnfYdf5
            a1szGRGUsidzKVlhQl5i1QtQvUrfRgX5Y25qFyjI3+FBHPTNhM8VCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T12:20:27Z"
    mac: ENC[AES256_GCM,data:q63duJMENRtzDTQfY65yRSzWd3OEmhiv4BbXbtPxQl6afINaO2agjchHLBUvBx6RdYCnkqw3Ee7LV8Ah0tnXOXCKza3s+b1LPBcV7xOHCAyR/j8Shk3jEvWRMc3K4TtLd5y3Zdlm6HlPejUMG6mO2hsCZrfbySCdKbnXUUtg1uk=,iv:FxaOXJ0Zq0+4JdxzE+1ba2u5/ZzwXi2Y+yKwXaSOWwc=,tag:DTyGJxvUX+YQXb9NDh6wrw==,type:str]
    version: 3.13.0
