apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:msY/MRU=,iv:1W83uTR0xXXcxGZ5Il3A/OOqC7RFb4uYx4BYJOSzlVk=,tag:UUlsUyevPXduRDYJVIPYKQ==,type:str]
    admin-password: ENC[AES256_GCM,data:J363Q22USb5PhNs=,iv:8xHuwPcWNKHKT+gZ7ufKYZMVLn2frv0SwIesaMPgAxQ=,tag:WWk2BoZgEW7ZMUFkO7D1gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNEV2UFdHaTlBQUxIWTNE
            OXhwTlFIQnpsZ0JLYjVXZnVrdkRZTEJSWkVFCmc2a3llS3hhSmoydkhVeHRPTlJN
            MlY0UEo4QWJMbVlPM1o4STZ6djRRRmcKLS0tIE9DbVloZkVEaWhsMmkvZWVzWnps
            NzRsL1FzemFlTmovbWJoRkkzZ0VpMTQKpKLC3FaHYHqrV8c0oYOqbUGDncdM70R9
            Fx58TKe0x8FK7E5j2mnDFYxyPD8J7WCj5ozkbSL5z+3csP15IrWwhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T22:26:34Z"
    mac: ENC[AES256_GCM,data:ot6ZvH1kvE2389V2ZC5hQftMtC63/E1x7modrhxpd8uYfYxY5byAniQvVpQLXVs9ySEVi3jZIAClnsBJiauaaxrUVGKVJ4lrsY8j6wytIHDsSDTTNWLfbPA0hDl4smAgYMM7/IuT24fWdp8dUrglgpcayLOwVXmLySj5JO/7jJw=,iv:Gv2eWxzYX8rsuRGYlOngfF/+EpCKyTu35LD0ZLwvG2I=,tag:6gtAQO2PfSoY4YQTM5s7DQ==,type:str]
    version: 3.13.3
