creation_rules:
  - path_regex: manifests/.*\.yaml
    encrypted_regex: ^(data|stringData)$
    age:
      - age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp

  - path_regex: talosconfig
    encrypted_regex: "^(ca|crt|key)$"
    age:
      - age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp

  - path_regex: kubeconfig.yaml
    encrypted_regex: "^(client-certificate-data|client-key-data|token|password|username)$"
    age:
      - age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
