creation_rules:
    - path_regex: manifests/.*\.yaml
      encrypted_regex: ^(data|stringData)$
      pgp: >-
          90CD2659E01438F54A298759396BBB691304AE0A,
          D42BCD76A5CFBBB7D7D576D1E1431177313EFCF0
