apiVersion: v1
clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRDZ0F3SUJBZ0lSQUtMcVlUVEswM3JZRFMwZ2lKNE5pZjh3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakExTURZeE56TXpOVEZhRncwek5qQTFNRE14TnpNegpOVEZhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRyUndmOWtNdzBSZmRFQjdxKzR2RG5GQlhRNTZoWXFhcEV2YWQxQytYYWNEWVN3Z3pKREhWTTRZNjYKb3N6ZDJGWTJLbE9lOXl4YndabFkvRUFNcXpyVG8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGSzRwYndEVU1Za1BPSnJDR0thWkE5Qlh3UUxoTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFEUy9RK1kKWU5MaWc5b0Y5YWY1cm4xdjZ4SmxkeVRnYXlUV2hnZGUxdmVaN3dJaEFPWVFjWHJnR0NENndJbFkwTG5CVkppSQptUit3SWM4NFFoRFp6VVZsTmFWUQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://10.0.0.10:6443
      name: homelab
contexts:
    - context:
        cluster: homelab
        namespace: default
        user: admin@homelab
      name: admin@homelab
current-context: admin@homelab
kind: Config
users:
    - name: admin@homelab
      user:
        client-certificate-data: ENC[AES256_GCM,data:Uf6fEXZhlFZveLVVT5vBCJMlCPPqZkYv1o+XdtYoC2HysjIcGV6zvtmXgKl1Pb7WRdY+Chx5n4eihyfnXOKVp0X9ZuNBlstBXIl5DlDDrlnPd2ia6+vCItzQcDkkaqCLTrGiNKjfWZIQH9Bm680fU3s4tl9OWcWoN+jsL++swh0D+p+CSBkf9utllTeXpM0ucW3mX8iDYBk6IaNynWmWaYPYpN6r+1Qc0lDjDJ01h4+IbiLfTow1k3Uy1lm5C731rdkArPExwpSZhjvK0SvARITMkFLapiojo3BzptxNepjT33xyDLUE/GDZAvs5gUdpbSERjRDKTm3yP15HzWVb8a2cxljAyjvu04WNloVx29IdFVQyGo9QD4YOq2ybwLHqScUc12yPGQ5VYxwRce4BQkjdaghnd7oKhuKRxhYtuWwDT8247LM3faB8Yyo2DpQ2Rk79mwren/3bArdDQsUgG6syfbDEg/CaLcF1f0OIPrsLn5PNhLp3o+HGEJehThsSUfkuPswUJcYizOUSy/8GFZ2Shbw6Qw2knsY9/40T6SpUb9rMCMI8cHqOcRP1MwjR478flic58CYMQlr7sZw5fGCUWvBG0sokpV9se9xD3vlfgpF55SxYrNq4Go7bPbwARhOiT57MrFMmCJqqpPut2NVgDvpPZlk1/4Tay8Uy6ycShldrju3hztFZflSpce/dBDettVyER4/RIddkdPN9FTix5dJj1gtaafsx+mNSOWy9j4lg+IyDq2y0cMgU6YBhvKwjKUEtC1C08WlSBZI71h4m7mIUmL14GMFR21OfWiJsQsWKQaKxj71SCiNP8pm68iLVBbh1MJyd2Xtaj98kIIDRiKFt036e+ZyokVd24kBpE3n+/BrV6qAnLyI5rMByu/yQbkDAxZYjx3C7bF4r8uoG97CcK5KqTBiM3HLKOgCex4BAMCsbtZXjGGEn+HcQ8MBq15SC4Qv6E4HfXxNA3u3s3fhon5aDHy017R8BNlAoDDgDo3wBli4+oUgp7U8yiqk+69cEYuvq3WSzixY4kw==,iv:0BMa6sRyp2svRMVxl1vaHYP6uVke/RJX7xz/RFhe/oc=,tag:dUkLRkHOnlGwp6nwEQVgwQ==,type:str]
        client-key-data: ENC[AES256_GCM,data:ex2RKuwwz/L9XThODJV/rBCVuus+b9V90jI9gDBUh38VXYWV4DkW+gQJVimPbfQVSxMG1pZrSKfeOjU4ZmK387DIY2ZqAglJ9QPvmHJ02tnRfWTTsghkYS/hGt2eYEfqPNzIbHKaZ5v00/85ueDRvrCj6TVx9TwkBJ0YeQ8V89c7dJllbSHS5908N+n+5dFendGt1arP7LCCjFHbGsGXkoYxf/Jl87ojyL4kGUra800FJDmFVezRpukmihffRQ6tIvygmQZFfj2BLvTc/afLEJTCef/Odp+5qb8L7wj2Ns8OmBkVwno39Pxyfy7u2ROZreuAyqEmewesiHuqFT1xMKgZ3CzHGY2HyWCZI2LvAVoC4x/TS6Rd/775p1b0eYQtyu4OYG9UPVqOGXbihnYaGQ==,iv:TAycnPy7Lly8pVyZLZegNhZiyN3emup4K6FueAllynE=,tag:6TuFX4W0th/yl3QL6qVDew==,type:str]
sops:
    age:
        - recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eFhGUmNpNlNvNDg0eURu
            N09qeG4wTjVwNFluaE9SbDMyeG5FOUF4VVdJCkRlTGk2Wm1lVzVDV3RLV1NDU0tF
            UXV3NDNNUnhnRlVVc3JGME1OZ0JxblEKLS0tIGszOUV6eWU1ZXNMaXNGYTM4aHBz
            WG8rTDJza0t3dm1KVm9IWXpNTXJWWUkKGRQzj9+un+yqfeQlPLQzM/N72baDiu1e
            LazgcK5zQy/z+OABtuIrEuBeYrm7m9CCP2fUzRptFv0uPSJW7SQp/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T14:52:41Z"
    mac: ENC[AES256_GCM,data:6ErDs722hut+PgvdGmZA3QIg2Iyg2gK4QTwdk+Vt6TsejbX1izsovTItpoH2zM5GQhMfjOdrHAwvONpfdEbIRao1SLSdhGbfGjpcul1P/xow5Kue4DYZgE0OCeiMt+6zDLLS0xgJ80ZM4F49oPkafAX5XjqsY6FAI8JKGkoi8fE=,iv:aNsKJDC1lsOfrww7uRIGHtoMTG20LWUqKqNagF1X51g=,tag:D14WA+Xa6TF0GU47wsY2gA==,type:str]
    encrypted_regex: ^(client-certificate-data|client-key-data|token|password|username)$
    version: 3.12.2
