apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: redis
    namespace: redis
spec:
    interval: 15m
    chart:
        spec:
            chart: ot-helm
            version: "0.21.0"
            sourceRef:
                kind: HelmRepository
                name: redis
                namespace: redis
            interval: 2h
