apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: networking
data:
    client-id: ENC[AES256_GCM,data:CD0fLBWDcbccz8lzq8yC7xhJHNIwnRCBrAthrg==,iv:sYA2FZszzj4JO9d86sbHZOVqx27H5KYmZrXfzTFgNws=,tag:qvoSgWRv04/0HUkOet9qPA==,type:str]
    client-secret: ENC[AES256_GCM,data:AD8I+zLivIc5DvwSrOqygGEu9BRu4RoVtj39Uqszhl5W7NP1dEj5YLMPBLw39cQtYsm1BGMXgpQ=,iv:0Yfckz/TC+pw9veiWY/JaxHHpSg5UGzeyiC4hK6b0RE=,tag:s5jkz7axgyoiicxcMy51dA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:w5YPkTfK051yNE6++SWnwD5XbaYrlDJfo5psV1IeYeY+uG1/kat4lvzilZM=,iv:WoB6qaFqKOp+/665emORe/H4yQugIqBUdl/+V5CxZ5s=,tag:7md+Zd67zr/202PHcIIx7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdTkwNmY1N3hLSGNwZGU4
            NGlsK3RpK1c3SC9IQzlkZk9CdTlJNDd0d2hFCitJQjhLK0hWN2ZYZ1BEMitDQkhD
            ZENOdGMwQnJrbVJETUVRY0laVkpxTGMKLS0tIDhMQ1VJTm1SOWxuREpsV0RIWUdw
            dm12N25Na0tUQ2t0U292QmdNbjZYWkUKBxfaieVh6tLIjEAiXoeLu9k4T7ZYWpO9
            v0yGiPNPWTilVD5Qi4DanuCUygGxwZGzdnH/GJl2TH9hmJ90k+y39Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T07:47:18Z"
    mac: ENC[AES256_GCM,data:BQyy/zfM4RVJBwxuI8JWjuYJfPyC3BNDK35whoppfRE+3upzmQdsNwNPM8ZtZXMxhvh2gt0NJ3Y/gRoqE1ivG1DFVUVTQebSYBgnz+7PeF5/jhE67y0+xedz5KxwBuEBI84+xPdtn450yi+HMEWx063jEd/khOY5gmSUlvEFGW8=,iv:XWOazQrlonambXn+Y0QPH556jXa5XhIlGJzp22En5Sc=,tag:SwrGiyqD0ILG82u3IS+u6A==,type:str]
    version: 3.13.2
