apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: networking
stringData:
    client-id: ENC[AES256_GCM,data:PgiNlHZbGJM5XVmUrxSedzXTT5o=,iv:ztio1nlxNNGxEohsgIUBB/hpzJPJP0YojQcQoyP3EMc=,tag:Jq8D7F3pJv9kQ2J+y2l+qA==,type:str]
    client-secret: ENC[AES256_GCM,data:WXqI7/AJjklBHCMu9OLm8Dn4mVG9YLB3v4zs4G3HNDJkLjBq4tWaFw==,iv:0qSAPsQeOOkBqSdQs2TobXBfVxOndi+nNHnVuhPrL20=,tag:nayUAIvPrzyhJzvz1IOuBw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:6aWhBRImjEQMiZBDKKdRXVHDuDTrtgT/J5LEbu6UerZcrgueyqPUKsOfNB4=,iv:aGB560687dhiF1uuXHKYrH0AlosFeiSKTM/uMJuCvaI=,tag:26ttmch4r4d7MXijqhhZVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNnMrZlprV2N4MTFzcHVC
            SXJwVlRIMmp3Y0RnNWxPdUpMR2ZRL0orUWlFCjRUVk1MVUg1NVVwTlRvdEFxZWVw
            cTZwdy82M2VLeG00NDB2U3FtRWpRemcKLS0tIFd4VC9jaFI4SUJSRkU0aVJyV1V0
            UDdMV2JjSFBGVVFtaGtnWDBHYS8rTkUKKa7bseUB6tvD/rNFoWEUoH7ujKFeC2Wf
            /Ybu2YHdIJnNcfNgfa74hoGzcWMEaKDKNg2Akaq5GFW0YFbfxia5UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T08:24:18Z"
    mac: ENC[AES256_GCM,data:DqrESozxXzRQzRLV/PEA9ouylcK5EXZn2tb2N3zJlsXJ6FCr+taDHXti9H2ycY0QaL86b90Yfwn2AqEsinuEPpdCjtQWXHSy60ba8nyJ+kqO1WnPGTkkLmrwxZs3lZDDuD6qS/9ttI6aPgpDdCD59eTbEELBNSzg3j/3icyZdQQ=,iv:MdBc8fyQ4V4l6NorV0sTQLLcrb3WkwV8I5+L03H/eL8=,tag:D10mPj0QQDC/jf/mGqOK2w==,type:str]
    version: 3.13.2
