apiVersion: v1
kind: Secret
metadata:
    name: deye-scraper-secret
    namespace: monitoring
type: Opaque
stringData:
    DEYE_HOST: ENC[AES256_GCM,data:as8nDVi0afGtcS0v,iv:KmVg81U87AZEXC0WPk6F92+0AjrSoGoQlliwrY7oF7M=,tag:v95qUWCUX0rWmQklVRW/sw==,type:str]
    DEYE_SERIAL: ENC[AES256_GCM,data:pqtdhWYZT4MjWQ==,iv:QwVp3i8ycc9s7HbdZz+zvSO/ROjwDsd4HsSaWjoQbTE=,tag:fWLL+NKTnzzB5BT3AqfKyA==,type:str]
    EXPORTER_PORT: ENC[AES256_GCM,data:vfmdsw==,iv:Qg0doj3nvOT+MXzL5n6t/AicC20sh9TS87xc505g5g0=,tag:tRpOaDdEwiZcw7fcz8QuaA==,type:str]
    POLL_INTERVAL: ENC[AES256_GCM,data:5Po=,iv:8a/6qhXnIvUDWt8hdt3lVwcwCltT3sG//EdJGTXEP0A=,tag:LPHmzF5LLJNKLbvF2Mu+FQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRlJYZnc5Q0F0WGxMelpW
            WWhVaEZJQjFPQ1FpT1dWTkYyMEwwclZzdVNzCkJoYU80dzJDdDdJZTJQT3dnRzd6
            UTMzenhzL1Fhb0IrYUY0WExpL1NMZ28KLS0tIG1xelFWS040SW5YWlhVMHJ5QjNG
            aU1SclE4cVZaQ3VSVkpVdHN1dk9BcjgKLMeIvNJ7xvdK2z6H1Ne9SEgEcW//2RdJ
            N6XYZ78p/MJq4B0lloSoeyW6u82mhBqh9BQw/8X0jx/e0bI/F1xWew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T21:48:48Z"
    mac: ENC[AES256_GCM,data:B366ZInNyALikGcLwfC6YRf+f02f+AtMOaLuvqXU5eLJdC6Z3nF/88eTJRAt68gmFLFbr4dZrO+sDySbRs4u+Cw5vUreqY43A8dBGT+VkUYvr4gDmPatwYBZE3RuS6rfYKkhu2HQyE4fuyzUipget3+26NysQqwB5+8zHtVAqos=,iv:dBDIAHSKJR5WKzveCtmR9lf+XSI6ovFEY2ZZTN9yZPQ=,tag:2aSEZ+RQIUuiNA+63UUj3Q==,type:str]
    version: 3.13.3
