apiVersion: v1
kind: Secret
metadata:
  name: deye-scraper-secret
  namespace: monitoring
type: Opaque
stringData:
  DEYE_HOST: ENC[AES256_GCM,data:CU0icAGk7ZJxkjhNxw==,iv:0ZHM48X/WgZZxdIGnW1rBcYNYQ3jHb7TWRqXKjGooEY=,tag:hKHMk1PtxC+nJ5UjZxmk2Q==,type:str]
  DEYE_SERIAL: ENC[AES256_GCM,data:DXrmHrY7TzYQ0Q==,iv:PuImhussC4eUaJAqbQpHK3Hl7ScrPSZqZ3RntpMvHck=,tag:OcS3paXaeiv8qOhssczCsg==,type:str]
  EXPORTER_PORT: ENC[AES256_GCM,data:S/8/7w==,iv:TrwGjeofXvvGSb9fb6tMkbcg94VuvDSHxVwQRprzz2Y=,tag:9tYCZDkHwfENdqwcxH6ppQ==,type:str]
  POLL_INTERVAL: ENC[AES256_GCM,data:qXM=,iv:udbptz7OBtXMefwqli9MR09aUwo4lTWBvuta3mCi8Mo=,tag:0nArYhRcRKFFDrf0iz0rnQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd2pKUTI3djRkTkxlQytH
        U0FPUUptOG5KL2YwTklTMENLZjl4blpkcmhVCmVndTR6Y25udEQxS0syVWkzNW1M
        YkVVWGt1Q0tQaGZLUTZIQkxzV2o3c2cKLS0tIGNQbFdWZzQ5eHZJV0pLWnpIMWV2
        WWQzZzdRcWs0RlE3RDRIcWRNakZSdTgKdKngjyXqUqgii/dL+XfY+DW1634VM1LH
        IFYfDVRdR+0Do3qdkW6h4VH4xTmoMgunJ+G6WPwPnfYzNg6RgeoVrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T18:08:58Z"
  mac: ENC[AES256_GCM,data:ntiqdhH5gtx+iiForoTZEni/Yt01+R7wxd2l+3l2MYe8EkbbSb92AGY13YpBhzs6lW6QC6gJ+GFtwZVv7/j834iuqiHUqZvcKryvMy2yMWP1B7N+uH+86ISyc1H2NIn12MoOLmxtQwbLLKBJY88G2+DekX2n52bfR4Gij20jEOQ=,iv:Fb8A5wBW2lynMKkXflB868FdoPOe7NdIf2L1LlRryGw=,tag:EbHh24rRJ97cJk1xFJf6BA==,type:str]
  version: 3.13.3
