apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: cloudflare
    namespace: flux-system
spec:
    interval: 30m
    path: ./manifests/infrastructure/cloudflare
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
