apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: infisical
    namespace: flux-system
spec:
    interval: 30m
    path: ./manifests/infrastructure/infisical
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
