apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - crds.yaml
  - cilium.yaml
  # - envoy.yaml
  - cert-manager.yaml
  - cluster-issuer.yaml
  - cloudflare.yaml
  - local-path-provisioner.yaml
  - cloudnative-pg.yaml
  # - redis.yaml
  # - databases.yaml
  # - spegel.yaml
  # - authentik.yaml
