apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: local-path-provisioner
    namespace: flux-system
spec:
    interval: 30m
    path: ./manifests/infrastructure/local-path-provisioner
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
