apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: infisical-db-cnpg
    namespace: infisical
spec:
    imageName: ghcr.io/cloudnative-pg/postgresql:17
    instances: 3

    storage:
        size: 1Gi
