apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
    name: redis-sentinel
    namespace: infisical
spec:
    clusterSize: 3
    podSecurityContext:
        runAsUser: 1000
        fsGroup: 1000
    redisSentinelConfig:
        redisReplicationName: redis-replication # Must match the name of an existing RedisReplication resource
    kubernetesConfig:
        image: quay.io/opstree/redis-sentinel:v8.0.3
        imagePullPolicy: IfNotPresent
        resources:
            requests:
                cpu: 101m
                memory: 128Mi
            limits:
                cpu: 101m
                memory: 128Mi
