---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
    name: redis-replication
    namespace: infisical
spec:
    clusterSize: 3
    podSecurityContext:
        runAsUser: 1000
        fsGroup: 1000
    kubernetesConfig:
        image: quay.io/opstree/redis:v8.0.3
        imagePullPolicy: IfNotPresent
        resources:
            requests:
                cpu: 101m
                memory: 128Mi
            limits:
                cpu: 101m
                memory: 128Mi
    storage:
        volumeClaimTemplate:
            spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                    requests:
                        storage: 256Mi
