apiVersion: v1
kind: Secret
metadata:
    name: messenger-clone-secret
    namespace: messenger-clone
type: Opaque
stringData:
    BETTER_AUTH_URL: ENC[AES256_GCM,data:9KyQMdHdgDRFglHSVIDrwZ6aHDUvp2DXMt/lli8GsukyO1afc+uuRrZEqg==,iv:30oZ71Wwrjv9MY5FPNssr5oMBqI/XAmH6lRsVg4mQbk=,tag:o5lxZQRHu/KIRAjPuqcIag==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:NgxBKbakvjDFTkiNi2w6C6D8cxgJjZPZKQQsg8lYSYoZPhXfCDyWLZGGRZ8=,iv:pChA3JOQpRtr23uZlw/+luK5cwMuaqAWeH9EeeBK1GA=,tag:NfDPovXXMju0Hqh+5NawNA==,type:str]
    CLOUDINARY_CLOUD_NAME: ENC[AES256_GCM,data:7GfjejWw0b6b,iv:GJDKAyaxd2VJm16ZadIpPwSrfj7sMw3opVgoIG9mtsg=,tag:bhNgIsoXJLiU1HTPZ3UAZQ==,type:str]
    CLOUDINARY_API_KEY: ENC[AES256_GCM,data:OT86tWsP3q509nwi/3rY,iv:Zjbqy3Ze2jZRokHW9t1f4miwzDaS3WtJQTYpPwqQknQ=,tag:57GuTgbJhqQFUMEgpShBBA==,type:str]
    CLOUDINARY_API_SECRET: ENC[AES256_GCM,data:lqOeFlwK8dYUdiwX7Vy7gA7u7rbxsP3olQkC,iv:sWdo7UPaYiL2O82T2RRLLzKytRZiOMf5H74sgapQQLc=,tag:2zU7zpMC4Hs4SNkfoyYFXg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:wZ2cMnVZsWqaJISqgw==,iv:vVHKy/oZaDXr/EofowXuxiB4XW4dv58ZYJmxozomhos=,tag:pU2sQOlC3ktyRTXC9ZC24A==,type:str]
    DATABASE_TOKEN: ENC[AES256_GCM,data:/FOWwoUGl84Ck32BqJjOZnHSuf9UYwiAJ5wDEqiMibkyt4GNKvIxzivRddI=,iv:bvxerTxnXsR3B8+mo2gLpE8S/H5m9beng3SJSf2pC+E=,tag:hjJ4Lpxlpo5cTh9WanxGAw==,type:str]
    PUBLIC_API_URL: ENC[AES256_GCM,data:cewHyugXZSyRNXPCxrqMpjG/m6X5xyZ3zOKK5AfJ1CHYNlwHgPTckRtKk6UyPhKHT7I0,iv:PLRtA+AYi+5r/k4Gcz7bZcZ3UgpoLWgm90FCak2rCMc=,tag:8PSWlB78rv5jcoIDiSu6QQ==,type:str]
    SITE_URL: ENC[AES256_GCM,data:MfmCXSzcsPH1+9udvf8XFNt8MuIodHjWo4VTxEWsherqJdS1l0eQYBeNEA==,iv:2E71RXP9XgdR3bByO9gDSs1YzvBflMrdVLVdC/QegIA=,tag:HJLR+AZiVH/K28KJIS5yhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRG9iNzlpSXkxcEZIbDdk
            TUNxU3RYZERIUlQ0aWNKdk90Z0VzZEw1UWdzCmVVS0pQbjNXOFpHSWNPZmxEM2lC
            YVZhNUY1RGF0TlduWHQrb3Y1RzBJa3cKLS0tIHZmOGI2WkliRmp4cWhSenF2a2Zy
            V1R4N0l1WUlsVWdLUEpkeitwNEVDTzgKdpHcgTbySjWF2SB5woMVecv+nvWQYh7p
            ZSEps+SMv9NO4NjHJWBlOfIoBLSj8Df0lNmNgVwbFvxO+LgAuJ0xHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T12:53:25Z"
    mac: ENC[AES256_GCM,data:kPZalF1/JGVB7+35/lrugVxNj8Kht1jRKBYuYu3ZTMPn25yUrV9TMAnNd9sJ3luaPclpSTGn3Zf4U0pPHHig9gJD1YauzvvIhpNbwnHYRh/y6eSluwnaXFyOt53uk3VHqDONZADJDrtxV3lAl/eV/xHy+q7XiFIgQPawZMAgD8o=,iv:pibKEFbxnPDtRz4h33AgjXsciCO3+4MQtDyRXOWsAdY=,tag:Uw5amU+JvYFQjzyFE+mqWg==,type:str]
    version: 3.13.1
