apiVersion: v1
kind: Secret
metadata:
    name: messenger-clone-secret
    namespace: messenger-clone
type: Opaque
stringData:
    BETTER_AUTH_URL: ENC[AES256_GCM,data:oDt/c/JP1riZ/XK4MpErNf7NsfRNEUc5sJBcnxaSJtBbsJrDcrkX6BwO4g==,iv:xJIv7nQHCpnCynUJzAG0rQjwdTAVM4shNuSpyqmt5go=,tag:i7WmS0Gk71GZcSPbfyR/UA==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:HLWcObz9NT4FnRL4Xn7hcbVqRNK4yBH/sEw7NBxQiuMrgZBF8MGLLJTVrcc=,iv:cr1lEuyfavZ29OeQEEb7wRHFCZGWSdRWom7ols6k17Y=,tag:VMHK5nPvvo7EQswJ7Xvg4g==,type:str]
    CLOUDINARY_CLOUD_NAME: ENC[AES256_GCM,data:aOnOrIAOn/mr,iv:rBAp5LAPGxw2J08Pn7wQ0V7EKCa/STkh3ZaN+eVbONs=,tag:BhJEa5fKZmVjdi/QWN8czQ==,type:str]
    CLOUDINARY_API_KEY: ENC[AES256_GCM,data:U+nTJ8qneErgJcckAckc,iv:VFzdT8j1OGH6fxax+097hTx/TGrg4xvqzB2QW65iGSk=,tag:y+LK/hDVYbEdN09qiFvyxA==,type:str]
    CLOUDINARY_API_SECRET: ENC[AES256_GCM,data:zKGN52VWZ5Qn5KYQ0f6S8/blR4w3KS6GWFYP,iv:RqeKJ4SnFsUI33NWUgo2lz9B8DTXJUvoRgGzeYyT4W8=,tag:3ITzl2QZfWUmHSNueJDghg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:vY+FAZQ5IFbi4eUljjapw0Bl,iv:+fF2rIlrEiOPtVy342/2IrBPt6Lq9r7x8psHfMiaaQ4=,tag:ZSMcTZLLSh41bskx5c/TNA==,type:str]
    DATABASE_TOKEN: ENC[AES256_GCM,data:Tc7dZLOm63VwpF6q+jLvWyTp8cWB7YOLP5lQrclCxLtHIVjDftJ7aTapDpUbdK26xt8iKsQfs/qo2A78oG1whRj4QSIqZdJIn9LknIlxqAxkeD3yVxR32oYbWagrI8OxZvHmIOWuKvHn2cqfeVjnc9yGOtdZYIUDaco/cCbg+A4pMbuQuynEMZctAOnXTU4JuyWr1sdSsBklpJYM8DsYCw==,iv:Vwzvf5waT3dCsshNbVGW598iaGKx1XI4dOZHAoZYej4=,tag:X/39P31I0yZDT2zpHAKiEg==,type:str]
    SQLD_AUTH_JWT_KEY: ENC[AES256_GCM,data:GD5Zf3VqTpwnwMrDZk05BC1/sBe+JRGLcMw7gkFwSuNp7I0M2bVgJSqw9g==,iv:my00CKvU8vI6LtSDGuIk0YU0N1cxHXqBw3UUjcbygyQ=,tag:B9VtNR6fWm+q+AVx2ry/TQ==,type:str]
    PUBLIC_API_URL: ENC[AES256_GCM,data:LvILKKwUW3CKLkWaATuh9UojcnH0Hd1mBQLB0BQzfOGXinxaqA5zSeq2zFKm1gHOpWvI,iv:mmfmnN17DM3STrA4v5HCwynQEHIFvW/5ozeKgM/8HwE=,tag:JGCVNrvX+5zndA8E5BLeAQ==,type:str]
    SITE_URL: ENC[AES256_GCM,data:euVqjEqPXZsDAUUe9anTuRph6tETdaozKRYBn3nBDoRwQvPsmqBpClwrIg==,iv:EGFZniYrlbJctmcEPnIlG5/LduygrMDJlv/Kjf6a9XA=,tag:J8UBRUBj5kpA2pffTrJh3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSHZrSGhDdEdIaW1VR252
            Q1loS092RzF5bStLdWhQVDZtYWRXTmNPakcwCjIyaU11cHBvSU93bVpKVXZWbW5q
            bG1XMmhvMGd5ZXM1M205djZObERkWVkKLS0tIFcvamVVV2hqei9yNWI2eTlWNFln
            Y1d6NDc3bENHejU0QUtISW4xMWQ1Y0EK7Et8hH5ZIWanhEVJcQmie+1U1Q99lKIh
            eaqPg5RgPyCRKC4JZ8rk2ABxHwd1u5XJa2VbO5UglzNV9v5VVQLHkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T22:28:04Z"
    mac: ENC[AES256_GCM,data:+yeGQY5SRTiWt84PcPzO2hkY5s3flL/m1P9hqZAWb0LrO6g5wQ8iKbbkiTjR2+sRVUCPcVEx2XfPXdCvWq8Anymkwk+n6kQz3UqKG4sfhYeAJCYs6cWieQglTDxqrk8rCMxn1wzhtLe5/tMTCUv+w+fM/cnVrr2EVu4CdUUgTRQ=,iv:3RBbLeqAwYqil6p1awUGMcBNsHPZ+tzckeL3EQwct4s=,tag:+di6PYtI3I3Gm4VmHRLPCQ==,type:str]
    version: 3.13.1
