apiVersion: v1
kind: Secret
metadata:
    name: messenger-clone-secret
    namespace: messenger-clone
type: Opaque
stringData:
    BETTER_AUTH_URL: ENC[AES256_GCM,data:2fr2ll8aQRHvJ9oWtpDnabs9I5f1e9+jjjXlUy13CdzeTP7HZnVY57gm0A==,iv:aNNrupury5smiLpx76HjHrzdnQvxcyFczU4RobUxIlY=,tag:dsj9O1NsYDnClQj9zYBW2g==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:2vtLbvjijv+nQOyAQRvL9SxZpbAAmwpqSmyjwEUE+Okh7aEOXSdqQOv5Vlk=,iv:342uTyWtRixNcxpR++0E4fGr66JS5Iqs/7Pq0A0tAs0=,tag:zlOZJFKVQtttZb3dQzhdxg==,type:str]
    CLOUDINARY_CLOUD_NAME: ENC[AES256_GCM,data:4+FKDUoLZNJM,iv:qlnKxbI/IDMOGVIBnX6WhfTDUs5zaZOuTOftmgdbM1A=,tag:F6eKum92D49hQmtFps8FYQ==,type:str]
    CLOUDINARY_API_KEY: ENC[AES256_GCM,data:Yqm6LN62EJYWXKEsk90v,iv:SdzdWYUVEyRezNvj7ATBUV10rJslUPTOAYWVr+Venqk=,tag:a9JmVfDJj9y7AMcvOaP09w==,type:int]
    CLOUDINARY_API_SECRET: ENC[AES256_GCM,data:OU9trXYLGnfvFhZUGAvebg2XdTvFVqIaTcMU,iv:xswi0xbMacT5gerEHeruOfi4REwH9TBE/XJla19HzZQ=,tag:yzob0eY9A8Prpnmtu1DjIQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:CdgLLGTTGM54NApV5A==,iv:vwE7MX2LZ4xE05CDuJJyItaM1oF2dWttiHCfCY4ZnV4=,tag:3o6mtmn+A5liZKNmupAr+Q==,type:str]
    DATABASE_TOKEN: ENC[AES256_GCM,data:gL77WJzq/hSBe+E86JwmMC9JdwSLznHZ3LBP7dfKVlfCsrkmtcoz/dIfWXE=,iv:Vb2umDEl2+czDbdZYw5zDZ+CNDZB6CVKxN++2Ca5X9U=,tag:NwlgQSVV/sKyvcCU8Ut/sw==,type:str]
    PUBLIC_API_URL: ENC[AES256_GCM,data:zzxtpdEyvUQC9fNv7uforPA5b/+FE7dj7L/sASMYA7t8CCwYVSsojryI8wfa9rnkzmlN,iv:uy5Xr4c/RDy36wZWjkP/V8lL1uWZZojhusON/iwPSQ8=,tag:9gZIvkUqc5PWWoBzEkLLoA==,type:str]
    SITE_URL: ENC[AES256_GCM,data:7eQwsIJdqauoHnVqsrvjNLtiZsTvg64SZIHlgBdWsTgG/HHJBJQs3Tsm2g==,iv:IX8QAyNHarZNYYwEvXSdjl6lJuGaAh5jeHA6urW4aHg=,tag:wVdn7D3YfgN1afIzxMkXAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Tk1Fa0tXQWxPTThnOGxC
            MUhlRHphelJqK2tZQkRMa3BFWXdLY21YQVcwCnVUb0kxd3lmL1ljQjZLdm92RlpZ
            Q2JIYUM5TlJNSHg5RldRTTVPQnFZdEkKLS0tIGk0QVZqa1JGN1NpK2hXVlZIUkFn
            bG9HdG14aVNGQjcybSsyQ1o3dzdRdWMKNzbnkG0GRQdIqggSrFglA+gyfSO+ptUK
            rtK8zVBlfZu78Ug07QJqJjtMrjAUOEk734x4TF7mrDKh+S/SO4PgNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T17:06:45Z"
    mac: ENC[AES256_GCM,data:FY+tk5XLO+GkcuH8aUYeR4E0nS7mNpbgifrkPIqRsYXGf5aOsFlgS9I72I5Rfpyu9W7ByDonZdrtIRWyLV3h0FB2ZnBMnQHOCcvF4JOkECgnTJW5SRsNCpaE8YF4rvOtZcO3wnPbJN6UY8SUrRaSfIbTI7iMYxLO2jSsAf/f5QY=,iv:bhynOfIWLuoV4/nmM/BzomWv7wod4Y5F86iiN8jya4g=,tag:99P6opQlJd/5tI7ciZStAQ==,type:str]
    version: 3.13.1
