# Render patches to later apply after nodes are created
- name: Render cluster hostname patch templates
  template:
      src: "{{ templates_directory }}/set-hostname.yaml.j2"
      dest: "{{ talos_directory }}/patches/generated/{{ item.hostname }}.yaml"
  loop: "{{ processed_nodes }}"
  tags:
      - hostname-patches
