# Set talosctl endpoint
- name: Update talosctl config (endpoint)
  ansible.builtin.command: talosctl config endpoint {{ control_plane_ip }} --talosconfig {{ config_file }}
  changed_when: true
  register: install_output
  tags:
      - update-cli

# Set talosctl node
- name: Update talosctl config (node)
  ansible.builtin.command: talosctl config node {{ control_plane_ip }} --talosconfig {{ config_file }}
  changed_when: true
  register: install_output
  tags:
      - update-cli
