apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: authentik-ext-authz
  namespace: networking
spec:
  services:
    - name: ak-outpost-authentik-embedded-outpost
      namespace: authentik
  resources:
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: authentik_ext_authz_cluster
      type: STRICT_DNS
      connect_timeout: 5s
      load_assignment:
        cluster_name: authentik_ext_authz_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: authentik-server.authentik.svc.cluster.local
                      port_value: 9000

    - "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
      httpService:
        serverUri:
          uri: http://authentik-server.authentik.svc.cluster.local:9000
          cluster: authentik_ext_authz_cluster
          timeout: 5s
        pathPrefix: "/outpost.goauthentik.io/auth/envoy"
        authorizationRequest:
          allowedHeaders:
            patterns:
              - exact: "cookie"
        authorizationResponse:
          allowedUpstreamHeaders:
            patterns:
              - prefix: "x-authentik-"
              - exact: "set-cookie"
          allowedClientHeaders:
            patterns:
              - exact: "cookie"
              - exact: "set-cookie"
      failureModeAllow: false
