apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: authentik
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-secret

  postgresql:
    parameters:
      max_connections: "100"
