apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
data:
    secret_key: ENC[AES256_GCM,data:4ds7xbUQqT3zjJ0dDhEA+T1zgpt9yyk8jG1Sipq1KeDerlK5miSZoTMxBB98dDBt71QZ4ERzmWqXkfpBLjO8crj7kgJpTlrpGCih/d/DGi0=,iv:gx+60/gJtCDTKCKYxEd0soagwKElXE9xoqET0mpj5w8=,tag:mTm0l3rvwSrMmeamP/iXOw==,type:str]
sops:
    age:
        - recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOUtWK0cvTHNZTXpBQ251
            dDZMTmYrQktkczRVZGFwdTJ1NFNwWnppSjAwCk5EcVZNbGVmT2RFWHJBSHhCMGU1
            RmVqdzBkREw4TG0vcVdXQ1BpbEI3TjAKLS0tIFNMNkQycFZZeTFOQk9PR1FNeU9Y
            UVNoRklQbjYwRFVnWkQvdVpiN3crZ3cKMNjPseRTU8pcZbSkoFREHGOVSSbZdeyy
            PSK0VTOwYKbksXhoJ8Y4ONNiGab9owDQ62tEQpSIpSkcdIfnXIABkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T11:37:42Z"
    mac: ENC[AES256_GCM,data:VDAZF9nUbAu1b5m8LnnyfeyknyivPMTDT7O/UUG1BrBoYo0/Ea5bzqCiiQUNLKvsK6MHNBYu2KRjkIjPL+0QkwwHL2hkM8l4kkNSFMBaXwMSjy8ocyjwjpuPgS0HY5EFQbkwrtUT3FljiBs70DKB0hV+qgutRpJftXQfZRwC+n0=,iv:G23ZlkOT1g4v86DEb30Vw1M+1lP5kC9obQ1IGH/4MEw=,tag:ssvfOzQ1eZed3C0O3n4f4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
stringData:
    username: ENC[AES256_GCM,data:7bZS59eFbsAX,iv:12KqJv7xif1mjetuPOai7+5OjEmmpdqBcDNYhPRN6Hk=,tag:iyHd1fhTj4TkhQjK+3/Xeg==,type:str]
    password: ENC[AES256_GCM,data:ZvNdvgZANXuKpwGCGpp1lS0=,iv:OvYUqvJm1DNez4fFl5OpZKa/v2qoiU3oBr/OE8Tzitg=,tag:3qgEtw81UYpBBXz0P5ryFg==,type:str]
sops:
    age:
        - recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOUtWK0cvTHNZTXpBQ251
            dDZMTmYrQktkczRVZGFwdTJ1NFNwWnppSjAwCk5EcVZNbGVmT2RFWHJBSHhCMGU1
            RmVqdzBkREw4TG0vcVdXQ1BpbEI3TjAKLS0tIFNMNkQycFZZeTFOQk9PR1FNeU9Y
            UVNoRklQbjYwRFVnWkQvdVpiN3crZ3cKMNjPseRTU8pcZbSkoFREHGOVSSbZdeyy
            PSK0VTOwYKbksXhoJ8Y4ONNiGab9owDQ62tEQpSIpSkcdIfnXIABkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T11:37:42Z"
    mac: ENC[AES256_GCM,data:VDAZF9nUbAu1b5m8LnnyfeyknyivPMTDT7O/UUG1BrBoYo0/Ea5bzqCiiQUNLKvsK6MHNBYu2KRjkIjPL+0QkwwHL2hkM8l4kkNSFMBaXwMSjy8ocyjwjpuPgS0HY5EFQbkwrtUT3FljiBs70DKB0hV+qgutRpJftXQfZRwC+n0=,iv:G23ZlkOT1g4v86DEb30Vw1M+1lP5kC9obQ1IGH/4MEw=,tag:ssvfOzQ1eZed3C0O3n4f4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
