apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:G2jtA3fPoaLNvp/ugBDMsuGtAtosU9HrnynomsUF2iS/d1PVC4z6ScEKHy/ZDbdEE+Qfcqs7HAD7YG4rkXTVPw==,iv:X7wt3epUtIW+YEDhBlcQrN/n1es1KBekah+Sb87pwMc=,tag:0XTEIRVXDYh54v4OrEKzcQ==,type:str]
    postgresql_password: ENC[AES256_GCM,data:OZEPr67BKbfRcqcAPkyCtz9fTZP/J+JDbY12tA==,iv:RPYxuA+qe+I7p9IPRrKyoatollWcRYxcWnPFDVnCkI8=,tag:YtZd7MVyVIJUCpm8qCsr+A==,type:str]
sops:
    age:
        - recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcDExYStNL1JSTFdTa1lR
            b2JMaDB4bmsyRnU3ZEFHNXRHVjhOOW56cWxJCjdwTXR6WXNDamZ6eDFwcTVsc3Vt
            SFJNNkM0TGR1OXQ0TXhhVVNQQjBQQ1EKLS0tIEdmT0E2cmJsb3NpcnpSRVRhY3ly
            dHUwOFZTU004aXRqaTVONDZoRS82U2MKFtpwvsOaiDHWa2Ju9PRUyjUoPRnOpCtn
            lEfwXHj3gBnwddu+oSlm8XPPDHsTtz9X7iWElE9wkd9E51TewF5z2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T08:33:23Z"
    mac: ENC[AES256_GCM,data:eyMewQdDUbeVJYy/59+AKTUyJvS8qtFtqCV1fnTmGczDpGBO+6/ilErPw76wQYiA7pil5VgsuMqYfq85/VfiJuv/pcYgGf3WOmp32VnomNkQOt9W599KdJJbHpoKBpdcnb50vfKNNaXvVepuZBxuXEEO3WXFQf53d6okt8jnewI=,iv:hQoupoA1h5sSfLGY44HMNFdgks27Us2D75kzWCsH0yU=,tag:Yl4flQXpp1rd7aMRZ6FNag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
