apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: authentik
data:
  secret_key: ENC[AES256_GCM,data:cizYD8sB96A9ucyzGflAcwgdM83IGp6fSJr2Ku6ZbjXz3MPQW+vG3lmi6Beqxx79BWAZ7KGLGVPemT6hFmHHBA==,iv:yr8QZwNs8oZ3sIEIXAwhyAeyyfgWVHqbB06EDOY1HxI=,tag:XGcN5skuPi5UsHufAN1cFA==,type:str]
  postgresql_password: ENC[AES256_GCM,data:mCk8jNUq4qWTv6qzMu5HqlNjtwGt6SEO0HOp4A==,iv:Fev1wg9A5LL1Fwo46ffupbZD4QHYlOZ7xOWINb9ndlQ=,tag:eGpV4OMHV1mcgCy0ros9+w==,type:str]
sops:
  age:
    - recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOampQb3d3cWhnUHgvWlgr
        UVhGalRRc3ZzMHJETFo4N3JOUUxoS2xiVEhBCmtNd3d1bFlaMFRVMDlMWE5wSTla
        aUpwSTNhb2pvRGMrdWFDOGtaUGVPQmMKLS0tIC8vRmlzSmpoTDlKQ2tiY1VqeHdY
        cU42Q0gxcmNwRGRxZm9zM095U2RRVzQKLFgXBSnxMzGCv4J9z5Yf+Fczhqu7tOrE
        fmdFjqPUPotm6yqmcIhwmGaIAItmu0we0GRIeSnZph+0mtP2v/EDYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T11:06:32Z"
  mac: ENC[AES256_GCM,data:NbAtzZUCgkP0Kz2aDGMrWPHpYLc9deCpDBZ+B0Op7HjAKkttLCrzvGt6mnsQni8vtLwOZnwNEPHBmBLq68Lbh0T8AXcEhGyW9wrHkGgpJ7WvQhyUQVGAoPxmoIWrPf/zd/YTVzyHaxMh/KUR+W+j2D9DY4+nfvyxiPqPeSuFUAM=,iv:zqvsFvHjKiniCVeD2L1c0Oas1DN2dv+zBl8p8r7P8ys=,tag:g4h/XOiR4xXf/V8nfWv65g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
