k8sServiceHost: "192.168.1.42"
k8sServicePort: 6443

kubeProxyReplacement: true

securityContext:
    capabilities:
        ciliumAgent:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
        cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE

ipam:
    mode: "kubernetes"

cgroup:
    hostRoot: /sys/fs/cgroup

hubble:
    enabled: true

    relay:
        enabled: true

    ui:
        enabled: true
