---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: local-path-provisioner
    namespace: kube-system
spec:
    interval: 15m
    url: https://charts.containeroo.ch
