---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: local-path-provisioner
    namespace: local-path-storage
spec:
    interval: 5m
    chart:
        spec:
            chart: local-path-provisioner
            version: "0.0.32"
            sourceRef:
                kind: HelmRepository
                name: local-path-provisioner
                namespace: local-path-storage
            interval: 1m
