---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: infisical
    namespace: infisical
spec:
    interval: 15m
    url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
