apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: traefik-crds
    namespace: traefik
spec:
    chart:
        spec:
            chart: traefik-crds
            version: "1.10.0"
            sourceRef:
                kind: HelmRepository
                name: traefik
                namespace: flux-system
    interval: 5m
    install:
        createNamespace: false
    upgrade:
        crds: Skip
