---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: traefik
    namespace: traefik
spec:
    interval: 15m
    chart:
        spec:
            chart: traefik
            version: ">=35.4.0 <37.0.0"
            sourceRef:
                kind: HelmRepository
                name: traefik
                namespace: traefik
            interval: 2h
    values:
        crds:
            enabled: true

        globalArguments:
            - "--global.checknewversion=false"

        additionalArguments:
            - "--serversTransport.insecureSkipVerify=true"
            - "--log.level=INFO"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
            - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

        deployment:
            enabled: true
            replicas: 1

        tlsStore:
            stores:
                default:
                    defaultCertificate:
                        secretName: mikolajmaciejak-dev-cert-tls

        ports:
            web:
                port: 80
                expose:
                    enabled: true
            websecure:
                port: 443
                expose:
                    enabled: true
                tls:
                    enabled: true

        ingressRoute:
            dashboard:
                enabled: false

        providers:
            kubernetesCRD:
                enabled: true
                ingressClass: traefik
            kubernetesIngress:
                enabled: true
                publishedService:
                    enabled: false

        rbac:
            enabled: true

        service:
            enabled: true
            type: LoadBalancer
            annotations:
                metallb.universe.tf/address-pool: homelab-lb-pool
            spec:
                LoadBalancerIP: 192.168.68.200
