apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cloudflare-cluster-issuer
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: myster123987@gmail.com
        privateKeySecretRef:
            name: cloudflare-cluster-issuer-account-key
        solvers:
            - dns01:
                  cloudflare:
                      email: myster123987@gmail.com
                      apiTokenSecretRef:
                          name: cloudflare-api-token-secret
                          key: api-token
              selector:
                  dnsZones:
                      - "mikolajmaciejak.dev"
