apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:Xj+XM3FcjweDkfBoPCoCq7uxwRm9X7DJjsRerbBeT93q0CoXYxacsxv3FzDr/ju4SiPp+03MCmo=,iv:EdYa+hn/SuihIrCY9XL4STt1BMxgaSfIK387UUpzcsA=,tag:RI4ipcSOdrlsUgJG7d4isg==,type:str]
sops:
    age:
        - recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTGlSNzdUQnJGdXVvejJJ
            L1ZmYW9WaGtuNFc5a0lmYUZFTk1sSkFjdEVNCkg4TURva1plakREUlFmMGJSMkd4
            WDBMemdOVGhYWEN3YmVKRHhEYVg0RFkKLS0tIEp0UVYwUHJkMjlTQkNsMlM2ZWZu
            eW8yQVBBNmVJc1BwWnYvRVhDTi9tL0UKiCEz1vhh0pJ3zdM2QSjH0A9gjWsTbopG
            khnYwE8JtgfVJpn+sL0kPbukfPWpnOq7MyB/GT5YcEbIEjVEBSMu4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T19:31:49Z"
    mac: ENC[AES256_GCM,data:8u0jAlNGAOQ5BzXLlhXwc0nleVdyL3M3qIrS+0DgaTMTSeUtkpQr18vhmLOWLF3DVlQDUZna3xD/xvtvsr1ZIaABQNPabRw8toRsw7UxD4DUaRUgtoGITHsLldfMAKVEFCDQrIYfYkBmuojZkcCe+CpfGYLQqnhygm716l9nMak=,iv:ESXVrmIlSGprBNlfVI0AtDCXE6l194x7UTROHmWy0jc=,tag:YW4iyxMogt9WtNcnKFaKNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
