---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: cloudflare-tunnel-remote
    namespace: cloudflare
spec:
    interval: 15m
    url: https://cloudflare.github.io/helm-charts
