apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: cloudflare
type: Opaque
data:
    cf-tunnel-token: ENC[AES256_GCM,data:OUzAQAwgquAg4tiN9CQ2147pt0EsK8f6jEkaeMn0r9JV3mVVDS2rJI8H/yZgQuqDo2ALhxra+wi+EEsFnOJXrvAp0U9TPB2/0PzR8+Wft0l7VJTiEC6Rt9wUpN0SqeCoYNzpRrHUvI/gJgE+NtV8rJOlWEYKNA/PQ7/k2wiqbWVqz4fwhQZrpGpOdGrYHT5rlSc9QyvCiHC8IS6LZMZ654nT3DdSRr0r6drGliCdDTKI1clENY6Ipk3r5Z5I1LrXsjOeKNvjLuylB7dpN5Jis6H5v1vx6GzDEPr+LwyvK1seHxjHYQ3FB43gUFbEwXD4MVjuEiM4+YY=,iv:V8SF2XHCRmT4cVTvAHyG1NdpZwbtTZASfJoEvWwzsgw=,tag:Y8jZDElkjwAuXSBQDfd5SA==,type:str]
sops:
    age:
        - recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU3k0MFBMVTh2V2dsdVJ3
            WVNHWnZETjNpS0YwejVGREZLK3NkTjE3OGpzCkxyRkJsQURnRmMxbEp0VFBLdjNG
            anNuZXN3UGNjQVl4b255QzRFQ1k3VzgKLS0tIG11bEFaZmhjZjVCZ05aeWpDcFNs
            dHhqYzlGdjEzcXNoSnpzTHM2MVJra3MKOgGcwixT714OoFYh7T6nRiZlPICiFWSg
            EgDg5GhOdSTIoaoG5kQ4rUghmlB87VGny+zNOKNPkJI805ZeyCLMYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T20:26:37Z"
    mac: ENC[AES256_GCM,data:c/cL/1DW40Atz7+eCgvG8ShXYYe5KGB29jbJLwjo7+jqpOQPcOpLQ1g7d78FRQ27aDIfqO2iG0d5oMVE6N5GXLfc1/PbQUUZatoQTKGDKmN58yEc8KGjEjPI17SOWdPkxXJAZ10ZdlWGbrQFCn67yCbbaF5SpyIe7YvdQ/1pJ3I=,iv:01DXyzYHt2a4xJYRk4V9tXaaYx+vZTRo1gB77o9xA80=,tag:dBit++nKop82l0e3IUBsLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
