apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secrets
  namespace: cloudflare
type: Opaque
stringData:
  cf-tunnel-token: ENC[AES256_GCM,data:8pBtc2PlxY5xtW0kAdaVM4sZ+Ofk4a5aWqi0xO7GlGO3I0p/RV25s7OKuitQxcshEsVs6QDYT4qJJ9xvo3B9X6KZX8cSLYOeXSEcKtbVIrZjyduDlKi9VG9bRP61Gz/iCzi5udsDy8LprxElykuqpbnB4GsdHbXP5jzzRUy5/jsEw4g96vEcJ1++xQ/n7h+1rdn5G6Bhal2PGFRzOp79IcTwqR6xypcgSxtEAq//WlE+a2v04zHi0Qmd77exEA2YYZt2n6XeeRYF3KeEFcSyCtI1tV/8BlF0idULe3Tma4JLcOD914lnqfXWJyCaLMYQwrA3Iciehfk=,iv:zDTTpyPqWUt206OAIek1uVQyD6465yzqqIhE6pV+rpk=,tag:HllWcEhiI56BBghdapCG4A==,type:str]
sops:
  age:
    - recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd1p2MCtRb0ZkL1BXYU9S
        RU13cDExSHl2V1hlOTNwQnVGd3lQNjNhRUVFClNhV1lGeVJLelpZdU1NR2xRSHRm
        WmR6VW1ZSHd3MnBZbTdrcGN6ck9IRzQKLS0tIHc3dUc5R0tVWlIvdGU1TnFtU282
        QUNIUWpzNzVZZTFZVXJnTFprbkFVVXcKQ9HIpqn0c+3Kee04uKc/8969A8aw4Roz
        1Q1eqgQjhVTwMWA3awDjo540bYiJCWD/OOspo8ux+GnueXO3Irdszg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-07T20:18:32Z"
  mac: ENC[AES256_GCM,data:rW0AUznLOHbm3Uzhgls3bbY1Hd6FLlg7YhjjDEKsa9uOF7sJ+10ownV6LVNFmvmc2u1Djf9buXKcgsJ+OXzT3Q/LPv0B2c3JN9T9uFfpWBum64F0ASzjqIEztWH6yxqIO54RdtFNh99fGYvMggmlQooYLKpUJx+MUw8meOQMuo8=,iv:wQoSxGkIzsLHQ2T1VED22W9ajEqtBESWtc8NZRUdKUU=,tag:v5B+D/dVZK/fn/2UItRyxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
