apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:KyX0BW+4fE7Zq5ref9l4tNNHrI2e0uP5dTwN19s0MwanBf+mNDXO8KU2wl7D1CoB6VV7cON2zy71vc1KnqFayW9UaJs0YKfBD1xHDQ+7x3S/rYirVmNLFqXPwUYD,iv:PqiHinmmrWW00XnXpl45g9nl9389132MAcUODzJaAUg=,tag:BRwqaIY1DIL12mDejbjOoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUU5sVk9iK0x2TTJUc3lT
            Q1JlK1Jyd3ZBSDlYR0pONGl6STAxTElWWjBjCjhIZ0pOOWxuUzhoMThPTkdSSkxu
            Unlsb3pzNnAwMkJOQlRRQ2JoK2hMbVkKLS0tIDU3c29ibFpSL3dZV2F4ZkJZYXEx
            RVlyamZ4UzVQQ2laL1NVTjZVYmRTamMKUl7/CdvNNw8tMhhunmL4P2obA0BogY8c
            zIZAk99z2U/gk6oWSAtupVczTYljzpDdtjc8noA15N7DTYBSAn7DrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ugf9cj0xugn9gxsvx3fdqzhldrgak9ltgwzqj54mkkeeg7tw442sgl0uxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T21:43:17Z"
    mac: ENC[AES256_GCM,data:r2g7ygp9VXoVNmoJYtCZeFHrCXl7rgaYXy2hWKM7bL+xOFjRFR0nfpzky9MV1Py3U8JAmnBBDtfmwIfw3Xu1ZkWrLrv3U3EJbLRtd+3rK9MaVgw+o6FhIOPQ3I2w9Yg46n/oO7Zaic1u+8vlFWQFBnJdH5kJmf957RtPS8HDk/o=,iv:QH+KeXAJq8QM5PWqv2nhDgwkzCYywY+YD+TvDDiW1Ls=,tag:BMLUxXfpAvxtDHjfW/IhAQ==,type:str]
    version: 3.13.3
