---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: jetstack
    namespace: cert-manager
spec:
    interval: 15m
    url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: cert-manager
spec:
    interval: 15m
    chart:
        spec:
            chart: cert-manager
            version: ">=v1.17.2 <1.18.2"
            sourceRef:
                kind: HelmRepository
                name: jetstack
                namespace: cert-manager
            interval: 2h
    values:
        installCRDs: true
